### ISSUE TITLE
Notify other plugin authors about PluginManager

### ISSUE THREAD

**Issue by maraf** [gitextensions/gitextensions.pluginmanager#7]
- [x] [volkanceylan/GitExtensions-SerenityFlow-Plugin](https://github.com/volkanceylan/GitExtensions-SerenityFlow-Plugin) (volkanceylan/GitExtensions-SerenityFlow-Plugin#2)
- [x] [amcarthur/Zipper](https://github.com/amcarthur/Zipper) (amcarthur/Zipper#1)
- [x] [EbenZhang/PReviewer](https://github.com/EbenZhang/PReviewer) (archived)
- [x] [otmopo3/GitExtensionsOpenSolutionPlugin](https://github.com/otmopo3/GitExtensionsOpenSolutionPlugin) (otmopo3/GitExtensionsOpenSolutionPlugin#2)
- [x] [andypaxo/ontime-git-extensions](https://github.com/andypaxo/ontime-git-extensions) (andypaxo/ontime-git-extensions#4)
- [x] [git-tfs/git-tfs-gitextensions-plugin](https://github.com/git-tfs/git-tfs-gitextensions-plugin) (git-tfs/git-tfs-gitextensions-plugin#20)

**Comment by mast-eu** [comment]
:+1: 
We should do this as soon as we have a release shipped and things are working. So we have something to show them :smirk:

**Comment by ivangrek** [comment]
Is it relevant?

**Comment by RussKie** [comment]
I believe it still is, there are benefits in making authors aware, which may ultimately lead to users benefiting from it as well.

@maraf @mast-eu have you made any contacts?

**Comment by maraf** [comment]
I completely forgot about this idea. None of the plugins mentioned above seems active, but I can fill an issue in each.

**Comment by mast-eu** [comment]
> @maraf @mast-eu have you made any contacts?

No, I never tried to contact other plugin authors.
Initially I had the idea to "polish" all plugin-related aspects just a little more before reaching out to others.
TBH, I never found the time for doing it and I doubt I will in the near future...
That said, if @maraf wants to make contacts, I have absolutely no objections.

**Comment by mast-eu** [comment]
For the sake of completeness, there's also https://github.com/ahmeturun/GitExtensions.GitLab.
The developer is already using the https://github.com/gitextensions/gitextensions.plugintemplate and there's a version available that can be installed through the PluginManager:  https://www.nuget.org/packages/GitExtensions.GitLab/
